### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by matheus-rodrigues00** [SaraCunhha/formulario-basico#4]
It would be great to have a descriptive **README.md** on this project, saying what it is about 🙂

**Comment by matheus-rodrigues00** [comment]
You closed this one but didn't create the README.md

**Comment by saracunhha** [comment]
I did 😮‍💨

Em sáb., 2 de mar. de 2024 às 14:50, Matheus Rodrigues <
***@***.***> escreveu:

**Comment by matheus-rodrigues00** [comment]
Sorry, I didn't saaawwww
